{
 "title": "Cloud Project Custom",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Create User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(method_createUserImpl_execution_time_milliseconds_sum) / sum(method_createUserImpl_execution_time_milliseconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(method_loginUserImpl_execution_time_milliseconds_sum) / sum(method_loginUserImpl_execution_time_milliseconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Create Shop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "    sum(method_createShopImpl_execution_time_milliseconds_sum) / sum(method_createShopImpl_execution_time_milliseconds_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}