name: Build with Gradle and Publish Coverage on Pages

on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    permissions:
      checks: write
      id-token: write
      contents: read
    uses: ./.github/workflows/build_only.yml
    secrets: inherit

  publish_on_pages:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: github-pages-folder
          path: ${{ github.workspace }}/github-artifacts/github-pages-folder
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ github.workspace }}/github-artifacts/github-pages-folder
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2