name: Build

env:
  INTEGRATION_TESTS_ENABLED: ${{ (startsWith(github.event.head_commit.message, '[ITENABLED]') || github.event.inputs.integrationTestsEnabled == 'true') && 'true' || 'false' }}

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      integrationTestsEnabled:
        type: boolean
        description: true to enable the integration tests with Localstack
        required: true
        default: false

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Create API Key File
        if: ${{ env.INTEGRATION_TESTS_ENABLED == 'true' }}
        env:
          LOCALSTACK_APIKEY: ${{ secrets.LOCALSTACK_APIKEY }}
        run: |
            mkdir -p cloud/infrastructure/src/testFixtures/resources/localstack && echo "$LOCALSTACK_APIKEY" > cloud/infrastructure/src/testFixtures/resources/localstack/apikey.secret
      - name: Build
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: |
              build
              -DIntegrationTestsEnabled=$INTEGRATION_TESTS_ENABLED
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: ${{ github.workspace }}/code-coverage-report/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 50
          fail_below_threshold: false
          publish_only_summary: false
      - name: Upload Test Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: ${{ github.workspace }}/code-coverage-report/build/reports/jacoco/testCodeCoverageReport/
      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY