name: Build

env:
  INTEGRATION_TESTS_ENABLED: ${{ (startsWith(github.event.head_commit.message, '[ITENABLED]') || github.event.inputs.integrationTestsEnabled == 'true') && 'true' || 'false' }}
  LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      integrationTestsEnabled:
        type: boolean
        description: true to enable the integration tests with Localstack
        required: true
        default: false

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: ${{ github.workspace }}/code-coverage-report/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 50
          fail_below_threshold: false
          publish_only_summary: false
      - name: Upload Test Coverage Reports
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: ${{ github.workspace }}/code-coverage-report/build/reports/jacoco/testCodeCoverageReport/
#     Pages are generated here to avoid a further checkout in the main branch pipeline
      - name: Generate Github Pages
        run: ./gradlew createGithubPagesDir
      - name: Upload Github Pages Folder
        uses: actions/upload-artifact@v3
        with:
          name: github-pages-folder
          path: ${{ github.workspace }}/github-pages
      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY